// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKYvUmSyD1A94I0RmwfFYQcvJzY9rakpE',
    appId: '1:131961058900:web:4cd85fc6eef803dfcd1fc1',
    messagingSenderId: '131961058900',
    projectId: 'ideapresupdated',
    authDomain: 'ideapresupdated.firebaseapp.com',
    storageBucket: 'ideapresupdated.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU4rUuTdu_PvtFjY016FseMaQmn4o9WOE',
    appId: '1:131961058900:android:217b09c15e1a30aacd1fc1',
    messagingSenderId: '131961058900',
    projectId: 'ideapresupdated',
    storageBucket: 'ideapresupdated.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJV2HvGEfvDROsnqge_UJ_5YPnncq24tk',
    appId: '1:131961058900:ios:69554eb6e740c139cd1fc1',
    messagingSenderId: '131961058900',
    projectId: 'ideapresupdated',
    storageBucket: 'ideapresupdated.firebasestorage.app',
    iosBundleId: 'com.example.geoSilent',
  );
}
